# Generated by Django 4.1.2 on 2022-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitypreference',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
    ]
